# Generated by Django 5.0.6 on 2024-07-06 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='empresa_id',
            new_name='empresa',
        ),
    ]
